### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by qmfrederik** [gnustep/apps-systempreferences#4]
@gcasa / @rfm thanks for releasing new versions of tools-make, libs-base, libs-gui and libs-back.  Would it be possible  to cut a new release of [apps-systempreferences](https://github.com/gnustep/apps-systempreferences), too?  This would help with making sure we package the latest version in msys2 (and Ubuntu would probably pick up this new release, too)

**Comment by rfm** [comment]
As requested, I made a release version 1.2.1 on github,  though I don't really see that anythimg to merit a release has changed (a couple of .gitignore filess added).

**Comment by qmfrederik** [comment]
Thanks, @rfm .  I believe the latest tag was [1.2.0](https://github.com/gnustep/apps-systempreferences/commits/systempreferences-1_2_0) which dates back to 2014.  Was there a more recent release which I had missed?
